apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "locust.fullname" . }}-config
  labels:
{{ include "locust.labels" . | indent 4 }}
data:
  docker-entrypoint.sh: |
    #!/bin/sh

    set -eu

    {{- if .Values.locustfiles.requirements }}
    pip install -r {{ .Values.locustfiles.requirements }}
    {{- end }}

    exec {{ .Values.loadtest.locustCmd }} $@
